apiVersion: v1
kind: ResourceQuota
metadata:
  name: backend-quota
  namespace: backend
spec:
  hard:
    limits.cpu: "1"
    limits.memory: 1Gi
    pods: "3"
    requests.cpu: "1"
    requests.memory: 1Gi
status: {}
