apiVersion: v1
kind: LimitRange
metadata:
  name: backend-limitrange
  namespace: backend
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 250m
      memory: 256Mi
    default:
      cpu: 250m
      memory: 256Mi
