apiVersion: v1
kind: ResourceQuota
metadata:
  name: frontend-quota
  namespace: frontend
spec:
  hard:
    limits.cpu: "1"
    limits.memory: 1536Mi
    pods: "10"
    requests.cpu: "1"
    requests.memory: 1536Mi
status: {}
