apiVersion: v1
kind: LimitRange
metadata:
  name: frontend-limitrange
  namespace: frontend
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    default:
      cpu: 100m
      memory: 128Mi

